### ISSUE TITLE
m2-sample-data - files 

### ISSUE THREAD

**Issue by price2b** [tzyganu/m2-sample-data#1]
marius do you have the chance to share the files of this installation (m2-sample-data) in a repository?. everytime i run the setup using alpha-101 says that /magento2/setup/controls/ some file is missing - consequently the magento setup tool is not display..
weird behavior but not matter how many times i reinstall , run composer install -> php -f dev\tools\Magento\Tools\View\deploy.php and php -f dev\tools\Magento\Tools\Di\compiler.php the same situation appear.
thank you so much, brgds!

**Comment by tzyganu** [comment]
@sebastianherrera I don't understand your problem. 
It worked for me. I just created a db, imported the db file then installed magento 2 over the database I just created.

**Comment by price2b** [comment]
thank you for the answer. in my case using alpha 101 setup didnt work. it seems that the app is looking for files located in localhost/magento2/setup but instead those files are in localhost\magento2\setup\module\Magento\Setup\view\magento\setup. for that reason i was asking if its possible to have a copy of the completed installed app to merge diff with my current fresh installation. 

types of problem i faced: 
- using your db i was able to create a local.xml, import the database and work localhost/magento2/ . but in my case i wasnt able to log into the admin area because the admin user is constantly rejected from the database, despite I configure a user admin.

brgds!

**Comment by tzyganu** [comment]
You should run composer install and then call in the browser `127.0.0.1/magento2/setup`. The setup wizard should work nicely. Don't use localhost. I don't know if the same problem that exists in Magento1 still exists here. Just to make sure, use 127.0.0.1 instead.  
I will close this issues since is not related to the sample data.
