### ISSUE TITLE
Column not found: 1054 Unknown column 'main_table.website_id' in 'where clause'

### ISSUE THREAD

**Issue by PrakashThapa** [tzyganu/m2-sample-data#3]
I got issue after using this sample data 
`Column not found: 1054 Unknown column 'main_table.website_id' in 'where clause'`
What can be the causes? thanks.

**Comment by tzyganu** [comment]
@PrakashThapa. Thanks for the report. To help me solve this issue please answer these questions:
- What page were you trying to view when this happened?  
- What Magento 2 alpha version are you using?

**Comment by quynhvv** [comment]
@tzyganu: 
I have take the same issue, when i try edit a product in back-end.
- I am using Magento ver. 0.1.0-alpha106
  Please help me, how to resolve this issue.
  Thanks.

**Comment by tzyganu** [comment]
@quynhvv @PrakashThapa. I've identified the problem. The fix will be available soon.

**Comment by tzyganu** [comment]
@PrakashThapa @quynhvv This should be fixed in the new version. Thanks for your help. If you spot other errors throw them in here.

**Comment by quynhvv** [comment]
@tzyganu : I have download the latest m2sample.sql, when i import to my database, i get a error:
[Err] 1065 - Query was empty
[Err] ;
[Msg] Finished - Unsuccessfully
I have detect & see a issue at line 2104, you are wrong with two ';' at end of SQL command.
Please check it again. Thanks.

**Comment by tzyganu** [comment]
@quynhvv. Thanks. I fixed it. It seams that the tool I'm using for restoring the db ignores these double semicolons.

**Comment by quynhvv** [comment]
@tzyganu: You are well come! My Skype id is "quynh.vv" can we chat more via Skype?

**Comment by quynhvv** [comment]
@tzyganu: When i try edit information of a Product in back-end and come back to Products list page, i get a error as bellow:
a:4:{i:0;s:85:"Item (Magento\Catalog\Model\Product\Interceptor) with the same id "166" already exist";i:1;s:7689:"#0 C:\wamp\www\mage2\app\code\Magento\Eav\Model\Entity\Collection\AbstractCollection.php(306): Magento\Framework\Data\Collection->addItem(Object(Magento\Catalog\Model\Product\Interceptor))
#1 C:\wamp\www\mage2\app\code\Magento\Eav\Model\Entity\Collection\AbstractCollection.php(1100): Magento\Eav\Model\Entity\Collection\AbstractCollection->addItem(Object(Magento\Catalog\Model\Product\Interceptor))
#2 C:\wamp\www\mage2\app\code\Magento\Eav\Model\Entity\Collection\AbstractCollection.php(904): Magento\Eav\Model\Entity\Collection\AbstractCollection->_loadEntities(false, false)
#3 C:\wamp\www\mage2\app\code\Magento\Backend\Block\Widget\Grid\Extended.php(476): Magento\Eav\Model\Entity\Collection\AbstractCollection->load()
#4 C:\wamp\www\mage2\app\code\Magento\Catalog\Block\Adminhtml\Product\Grid.php(204): Magento\Backend\Block\Widget\Grid\Extended->_prepareCollection()
#5 C:\wamp\www\mage2\app\code\Magento\Backend\Block\Widget\Grid.php(409): Magento\Catalog\Block\Adminhtml\Product\Grid->_prepareCollection()
#6 C:\wamp\www\mage2\app\code\Magento\Backend\Block\Widget\Grid\Extended.php(503): Magento\Backend\Block\Widget\Grid->_prepareGrid()
#7 C:\wamp\www\mage2\app\code\Magento\Backend\Block\Widget\Grid.php(470): Magento\Backend\Block\Widget\Grid\Extended->_prepareGrid()
#8 C:\wamp\www\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(651): Magento\Backend\Block\Widget\Grid->_beforeToHtml()
#9 C:\wamp\www\mage2\lib\internal\Magento\Framework\View\Layout.php(468): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 C:\wamp\www\mage2\lib\internal\Magento\Framework\View\Layout.php(444): Magento\Framework\View\Layout->_renderBlock('product.grid')

Can you tell me, how to resolve it? Thanks.

**Comment by tzyganu** [comment]
@quynhvv This should be fixed now.

**Comment by quynhvv** [comment]
@tzyganu Thank you so much!
