### ISSUE TITLE
Can not edit a product of any attribute set: Cameras, Computer, CPU, Furniture, Hard Ware, Monitors, RAM, Shirts T,Shoes

### ISSUE THREAD

**Issue by quynhvv** [tzyganu/m2-sample-data#4]
@tzyganu : When i edit a product of attribute set with named: Cameras, Computer, CPU, Furniture, Hard Ware, Monitors, RAM, Shirts T,Shoes
I have get a error as bellow:
a:4:{i:0;s:77:"Element with ID 'catalog.product.edit.tab.downloadable.links' already exists.";i:1;s:7953:"#0 C:\wamp\www\mg2-107\lib\internal\Magento\Framework\View\Layout\Data\Structure.php(55): Magento\Framework\Data\Structure->createElement('catalog.product...', Array)
#1 C:\wamp\www\mg2-107\lib\internal\Magento\Framework\View\Layout.php(679): Magento\Framework\View\Layout\Data\Structure->createStructuralElement('catalog.product...', 'block', 'Magento\Downloa...')
#2 C:\wamp\www\mg2-107\var\generation\Magento\Framework\View\Layout\Interceptor.php(442): Magento\Framework\View\Layout->createBlock('Magento\Downloa...', 'catalog.product...', Array)
#3 C:\wamp\www\mg2-107\app\code\Magento\Downloadable\Block\Adminhtml\Catalog\Product\Edit\Tab\Downloadable.php(183): Magento\Framework\View\Layout\Interceptor->createBlock('Magento\Downloa...', 'catalog.product...')
#4 C:\wamp\www\mg2-107\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Downloadable\Block\Adminhtml\Catalog\Product\Edit\Tab\Downloadable->_toHtml()
#5 C:\wamp\www\mg2-107\app\code\Magento\Backend\Block\Widget\Tabs.php(396): Magento\Framework\View\Element\AbstractBlock->toHtml()

....

Please check again the sample data & tell me how to resolve it.
Thanks.

**Comment by quynhvv** [comment]
@tzyganu : I have found the solution for issue #4, we need to re-save all Product Templates: Cameras, Computer, CPU, Furniture, Hard Ware, Monitors, RAM, Shirts T,Shoes
before edit any products of these attribute set (Product templates).

**Comment by tzyganu** [comment]
@quynhvv This should be fixed now.
